queue_rules:
  - name: default
    conditions:
      - status-success=tox27
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration-tests (ga)
      - status-success=test-collection

pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - author=ktdreyer
      - status-success=tox27
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration-tests (ga)
      - status-success=test-collection
      - base=master
    actions:
      queue:
        name: default
        method: rebase
