queue_rules:
  - name: default
    queue_conditions:
      - author=ktdreyer
      - status-success=tox27
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration-tests (ga)
      - status-success=test-collection
      - base=master
    merge_conditions:
      - status-success=tox27
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration-tests (ga)
      - status-success=test-collection
    merge_method: rebase

pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions: []
    actions:
      queue:
