#!/usr/bin/python3
import argparse
from argparse import RawTextHelpFormatter
import sys
from os.path import abspath, dirname, join
import yaml
from operator import itemgetter
from collections import defaultdict

# Import common_koji from the local "module_utils" directory.
working_directory = dirname(abspath((__file__)))
module_utils_path = join(dirname(working_directory), 'module_utils')
if module_utils_path not in sys.path:
    sys.path.insert(0, module_utils_path)
import common_koji  # NOQA: E402


DESCRIPTION = """
This tool queries Koji for all the tags and their settings.
It then writes an Ansible playbook to STDOUT.

Use this tool to quickly get started with koji-ansible, or to transfer
a configuration from one Koji instance to another.
"""


QUERYOPTS = {'order': 'name'}


def interrogate_tags(session, tags):
    """
    Interrogate Koji for all information about these tags.

    Quickly get all the information we need from Koji with as few XML-RPC
    calls as possible.
    """
    # The multicall() "batch" feature and context manager feature are
    # available in Koji 1.18 or newer.
    # Note: without batching, this client multiCall method bombs out after
    # about 35 minutes for large Koji task lists (tested with 11,170 tags).
    # Batching is essential. This performance also decreases as we add more
    # features (additional calls) to this code as well.
    # (I wonder if we could dynamically re-try with smaller batches if a
    # larger batch value times out?)
    with session.multicall(strict=True, batch=100) as m:
        for tag in tags:
            tag_name = tag['name']
            m.getInheritanceData(tag_name)
            m.listPackages(tag_name)
            m.getTagExternalRepos(tag_name)
        multicall_results = m.call_all()

    # flatten multicall results:
    multicall_results = [result[0] for result in multicall_results]
    # Parse into individual "inheritances" and "packages" lists:
    tags_data = []
    multicall_results_iter = iter(multicall_results)
    for multicall_result in multicall_results_iter:
        result = {'inheritance': multicall_result}
        result['packages'] = next(multicall_results_iter)
        result['external_repos'] = next(multicall_results_iter)
        tags_data.append(result)

    results = []
    for tag, tag_data in zip(tags, tags_data):
        tag['inheritance'] = tag_data['inheritance']
        tag['packages'] = tag_data['packages']
        tag['external_repos'] = tag_data['external_repos']
        # TODO:
        # tag['groups'] = tag_data['groups']
        if tag['perm_id']:
            perm_name = common_koji.get_perm_name(session, tag['perm_id'])
            tag['perm'] = perm_name
            del tag['perm_id']
        results.append(tag)
    return results


def koji_tag_inheritance(rules):
    """ Transform "getInheritanceData" result into Ansible-formatted data. """
    inheritance = []
    rules = sorted(rules, key=itemgetter('priority'))
    for rule in rules:
        representation = {'parent': rule['name'],
                          'priority': rule['priority']}
        inheritance.append(representation)
    return inheritance


def koji_tag_packages(packages):
    """ Transform "listPackages" result into Ansible-formatted data. """
    packages = sorted(packages, key=itemgetter('package_name'))
    results = defaultdict(list)
    for package in packages:
        owner_name = package['owner_name']
        results[owner_name].append(package['package_name'])
    return dict(results)


def koji_tag_external_repos(repos):
    """ Transform "getTagExternalRepos" result into Ansible-formatted data. """
    results = []
    repos = sorted(repos, key=itemgetter('priority'))
    for repo in repos:
        representation = {'repo': repo['external_repo_name'],
                          'priority': repo['priority']}
        results.append(representation)
    return results


def koji_tag_tasks(tags):
    """ Generate the YAML data for all koji tags. """
    tasks = []
    for taginfo in tags:
        name = 'configure koji tag %s' % taginfo['name']
        # Do not configure tag ID numbers:
        del taginfo['id']
        # Do not configure things if they're "false" or "None":
        for key in taginfo.copy():
            if not taginfo[key]:
                del taginfo[key]
        if 'external_repos' in taginfo:
            parsed_repos = koji_tag_external_repos(taginfo['external_repos'])
            taginfo['external_repos'] = parsed_repos
        if 'inheritance' in taginfo:
            parsed_inheritance = koji_tag_inheritance(taginfo['inheritance'])
            taginfo['inheritance'] = parsed_inheritance
        if 'packages' in taginfo:
            parsed_packages = koji_tag_packages(taginfo['packages'])
            taginfo['packages'] = parsed_packages
        task = {
            'name': name,
            'koji_tag': taginfo,
        }
        tasks.append(task)
    return tasks


def koji_target_tasks(targets):
    """ Generate the YAML data for all koji tags. """
    tasks = []
    for targetinfo in targets:
        name = 'configure koji target %s' % targetinfo['name']
        koji_target = {
            'name': targetinfo['name'],
            'build_tag': targetinfo['build_tag_name'],
            'dest_tag': targetinfo['dest_tag_name'],
        }
        task = {
            'name': name,
            'koji_target': koji_target,
        }
        tasks.append(task)
    return tasks


def generate_playbook(tasks):
    """ Generate a playbook YAML from a set of tasks. """
    playbook = {'tasks': tasks}
    text = yaml.dump(playbook, default_flow_style=False, sort_keys=False)
    text = text.replace('\n- ', '\n\n- ')
    print(text)


def parse_args():
    """ Parse CLI options """
    parser = argparse.ArgumentParser(description=DESCRIPTION,
                                     formatter_class=RawTextHelpFormatter)
    parser.add_argument('--profile', default='koji',
                        help='koji client profile (defaults to "cbs")')
    parser.add_argument('--regex',
                        help='match a subset of tags and targets (by name). '
                             'If you specify "foo", this will also match '
                             '"foo-bar".')
    return parser.parse_args()


def search(session, type_, rpc_name, regex):
    """ Search Koji for a type according to a regex
    :param session: KojiSession
    :param str type_: "tag" or "target"
    :param str rpc_name: Batch up this RPC method to find the details for this
                         type. For example 'getTag' or 'getBuildTarget'.
    :param str regex: regular expression to match
    """
    matches = session.search(regex, type_, 'regexp', QUERYOPTS)
    with session.multicall(strict=True, batch=100) as m:
        virtual_calls = []
        for match in matches:
            rpc_method = getattr(m, rpc_name)
            virtual_call = rpc_method(match['name'])
            virtual_calls.append(virtual_call)
        m.call_all()
    return [call.result for call in virtual_calls]


def generate_tags_playbook(session, regex):
    if regex:
        tags = search(session, 'tag', 'getTag', regex)
    else:
        tags = session.listTags(queryOpts=QUERYOPTS)
    print('querying %i tags' % len(tags), file=sys.stderr)
    tags = interrogate_tags(session, tags)
    tasks = koji_tag_tasks(tags)
    generate_playbook(tasks)


def generate_targets_playbook(session, regex):
    if regex:
        targets = search(session, 'target', 'getBuildTarget', regex)
    else:
        targets = session.getBuildTargets(queryOpts=QUERYOPTS)
    print('querying %i targets' % len(targets), file=sys.stderr)
    tasks = koji_target_tasks(targets)
    generate_playbook(tasks)


def main():
    args = parse_args()
    session = common_koji.get_session(args.profile)
    generate_tags_playbook(session, args.regex)
    generate_targets_playbook(session, args.regex)


if __name__ == '__main__':
    main()
